const photos = [{
  title: "Mushroom in Leaves",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/woodland-mounds-002/UhwnlByDQB7jnwpT_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "September 10th, 2017",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Trees in the fall",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/n-east-ia-001/ei7lmB06kuPL6GoO_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "October 9th, 2018",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Pretty flowers",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/jester-002/dOSGlzviN0mVnZtx_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "August 30th, 2018",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Pretty trees",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/jester-002/PpZEGCBnuvHYOquu_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "August 30th, 2018",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Lake with trees around",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/yellow-banks-001/EHAPgBFOOgW0TqfR_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "August 12th, 2018",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Sunflower",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/neal-016/VtbfPfbixPjuIlAw_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "August 6th, 2018",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Blue Dragonfly",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/ahquabi-002/LSMREjHr0yaLbcYA_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "July 5th, 2018",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "On I-35 Northbound",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/road-001/i8W3zIZKVnsT_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "May 2nd, 2018",
  tags: ["camera:Canon EOS80D", "t:on the road"],
},
{
  title: "Butterfly on a flower",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/neal-013/aF1h4nbGlWLm_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "August 16th, 2017",
  tags: ["camera:Canon EOS80D", "t:bugs"],
},
{
  title: "Peering over the edge",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/neal-011/zaDnAJV0C0c7_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "June 16th, 2017",
  tags: ["camera:Canon EOS80D", "t:bugs"],
},
{
  title: "Burst of Sunset",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/neal-010/PWuS2HF60q2M_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "June 14th, 2017",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Tunnel of Trees",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/neal-008/GcWyuDMlnKzw_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "February 19th, 2017",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Barn Bridge",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/lake-easter-001/RrON2w4U3ZjY_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "October 9th, 2016",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Babbling Brook",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/jester-001/h7957ccxcs_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "September 10th, 2016",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Cucumber Beetle",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/ahquabi-001/u62jih6zd4_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "August 28th, 2016",
  tags: ["camera:Canon EOS80D", "t:bugs"],
},
{
  title: "A Friend of All",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/capitol-001/pJJuZm960tBz_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "July 9th, 2016",
  tags: ["camera:Canon EOS80D", "t:nature"],
},
{
  title: "Purples and Blues",
  src: "https://d3rjsdgb9hzkgz.cloudfront.net/deck/summer-storm-001/2xEs9Md526Zs_50pct.jpg",
  camera: "Canon EOS 80D",
  lens: "-",
  datetime: "July 17, 2016",
  tags: ["camera:Canon EOS80D", "t:nature"],
}
];
